DROP TABLE IF EXISTS auths;

CREATE TABLE auths (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   -- status: {1: active, 2: inactive, 3:locked}
   status SMALLINT NOT NULL DEFAULT 2,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP
);
CREATE INDEX idx_users_email ON auths(email);
CREATE INDEX idx_users_username ON auths(username);
