spring:
  application:
    name: chatserver
  datasource:
    url: jdbc:postgresql://localhost:5433/chatservices
    username: postgres
    password: minhhung2511
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
#    hibernate:
#      ddl-auto: update
    show-sql: true
    open-in-view: true
  flyway:
    create-schemas: true
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
    postgresql:
      transactional-lock: true
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG
